version : 2.x.{build}

clone_folder: C:\Project

environment:
    global:
        # MSVC Express 2008's setenv.cmd failes if /E:ON and /V:ON are not
        # enabled in the batch script interpreter
        CMD_IN_ENV: cmd /E:ON /V:ON /C .\appveyor\run_with_env.cmd

    matrix:
        # For Python versions available on Appveyor, see
        # https://www.appveyor.com/docs/windows-images-software/#python
      - {PY_VER: "27", PY_ARCH: "32"}
      - {PY_VER: "27", PY_ARCH: "64"}
      - {PY_VER: "38", PY_ARCH: "32"}
      - {PY_VER: "38", PY_ARCH: "64"}
      - {PY_VER: "37", PY_ARCH: "32"}
      - {PY_VER: "37", PY_ARCH: "64"}
      - {PY_VER: "36", PY_ARCH: "32"}
      - {PY_VER: "36", PY_ARCH: "64"}
      - {PY_VER: "35", PY_ARCH: "32"}
      - {PY_VER: "35", PY_ARCH: "64"}
      - {PY_VER: "34", PY_ARCH: "32"}
      - {PY_VER: "34", PY_ARCH: "64"}

    OPENSSL_VERSION: "1_1_1d"
    POSTGRES_VERSION: "11_4"

    PSYCOPG2_TESTDB: psycopg2_test
    PSYCOPG2_TESTDB_USER: postgres
    PSYCOPG2_TESTDB_HOST: localhost

    PGUSER: postgres
    PGPASSWORD: Password12!
    PGSSLMODE: require

    # Select according to the service enabled
    POSTGRES_DIR: C:\Program Files\PostgreSQL\9.6\

    # The python used in the build process, not the one packages are built for
    PYEXE: C:\Python36\python.exe

matrix:
    fast_finish: false

services:
    # Note: if you change this service also change POSTGRES_DIR
    - postgresql96

cache:
  # Rebuild cache if following file changes
  # (See the file to zap the cache manually)
  - C:\Others -> scripts\appveyor.cache_rebuild

# Script called before repo cloning
# init:

# Repository gets cloned, Cache is restored

install:
    - "%PYEXE% scripts\\appveyor.py install"

# PostgreSQL server starts now

build: off

build_script:
    - "%PYEXE% scripts\\appveyor.py build_script"

after_build:
    - "%PYEXE% scripts\\appveyor.py after_build"

before_test:
    - "%PYEXE% scripts\\appveyor.py before_test"

test_script:
    - "%PYEXE% scripts\\appveyor.py test_script"


# vim: set ts=4 sts=4 sw=4:
